### ISSUE TITLE
Duplicate-post crashes wordpress

### ISSUE THREAD

**Issue by emsi68219** [Yoast/duplicate-post#212]
WordPress-Version 5.8.2
Aktuelles Theme: Hello Elementor (Version 2.4.1)
Aktuelles Plugin: Yoast Duplicate Post (Version 4.2)
PHP-Version 8.0.12

Version 4.2 | Von Enrico Battocchi & Team Yoast | Details ansehen
 Dieses Plugin konnte nicht richtig geladen werden und wird im Wiederherstellungsmodus angehalten.

Ein Fehler vom Typ E_ERROR wurde in der Zeile 145 der Datei /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-content/plugins/duplicate-post/admin-functions.php verursacht. Fehlermeldung: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-content/plugins/duplicate-post/admin-functions.php:145 Stack trace: #0 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-content/plugins/duplicate-post/admin-functions.php(145): in_array('post_format', NULL, true) #1 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-content/plugins/duplicate-post/admin-functions.php(40): duplicate_post_plugin_upgrade() #2 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-includes/class-wp-hook.php(303): duplicate_post_admin_init('') #3 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #4 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #5 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-admin/admin.php(175): do_action('admin_init') #6 /homepages/11/d13459072/htdocs/WordPress1/VanDerVoordenPhotography/wp-admin/index.php(10): require_once('/homepages/11/d...') #7 {main} thrown

**Comment by enricobattocchi** [comment]
Hi @emsi68219, 
we're sorry for the problem you're experiencing.
To help us understand what happened, can you inspect your database for `duplicate_post_taxonomies_blacklist` in the `options` table and tell us which value it's set to?

**Comment by emsi68219** [comment]
Sorry, meanwhile I switched to another Plugin.
